name: myspace_flutter_tool
description: "MySpace Flutter Tool"
homepage: www.shoh.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # FCode packages START
  myspace_design_system: ^0.0.1
  myspace_core: ^0.0.1
  # FCode packages END

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true